name: Deploy to ECR

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: demo-image
  REGISTRIES: "339713111450.dkr.ecr.us-east-1.amazonaws.com/demo-repo"  # Space-separated list of registries

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "buildnumber=${GITHUB_RUN_ID}"

    - name: Tag and Push image to Multiple Registries
      run: |
        for registry in $REGISTRIES; do
          IMAGE_ID=$registry
          BUILD_NUMBER=${{ github.run_number }}
          echo "Tagging Image: $IMAGE_ID:$BUILD_NUMBER"
          docker tag $IMAGE_NAME $IMAGE_ID:$BUILD_NUMBER
          echo "Pushing Image: $IMAGE_ID:$BUILD_NUMBER"
          docker push $IMAGE_ID:$BUILD_NUMBER
        done
    - name: start lambda container using boto3
      run: python ./containerfiles/lambda-container-run.py