name: Deploy to ECR

on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: demo-image
  REGISTRIES: "ghcr.io/aws.ecr.registry.com/another.registry.com"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "buildnumber=${GITHUB_RUN_ID}"
    - name: Tag image
      run: |
         IMAGE_ID=$REGISTRIES/$IMAGE_NAME
         BUILD_NUMBER=${{ GITHUB_RUN_ID }}
         docker tag $IMAGE_NAME $IMAGE_ID:$BUILD_NUMBER

    - name: Push image
  run: |
    IMAGE_ID=$REGISTRIES/$IMAGE_NAME
    BUILD_NUMBER=${{ GITHUB_RUN_ID }}
    docker push $IMAGE_ID:$BUILD_NUMBER