name: Build and Push to Private ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Authenticate with AWS ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        export AWS_REGION=$AWS_REGION
        aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_REPO

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag $AWS_ECR_REPO

    - name: Tag Docker Image for ECR
      run: docker tag $AWS_ECR_REPO $AWS_ECR_REPO:$IMAGE_TAG

    - name: Push Image to Private ECR
      run: docker push $AWS_ECR_REPO:$IMAGE_TAG
