name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build Docker Image
      run: |
        IMAGE_TAG=${{ steps.login-ecr.ouputs.registry }}/$ {{ secrets.ECR_REPOSITORY }}:latest
        docker build -t $IMAGE_TAG
    - name: Push Docker Image
      run: |
         IMAGE_TAG=${{ steps.login-ecr.ouputs.registry }}/$ {{ secrets.ECR_REPOSITORY }}:latest
             docker push $IMAGE_TAG
